<p >
    Dear <?php echo $staff_name; ?>,
</p>

<p >
    Thank you for considering employment with our company.
</p>

<p >
    We have carefully reviewed your credentials in connection with our current requirements. Regretfully, we are unable to consider you for a suitable position at this time but we will certainly contact you should an opportunity arise in the future.  

</p>
<p >
    We appreciate your interest in Remote Staff Inc. and wish you every success in the future. 
</p>
<br>
<p >
    Very truly yours,
</p>
<?php echo $signature_template?>