<p>
    Dear <?php echo $staff_name; ?>,
</p>

<p>
    We would like to check if you are still interested and actively looking for either a home or office based career opportunity.
</p>

<p>
    If yes, you are re-confirming that you are truly committed to building a career with Remote Staff Clients,

</p>
<p>
    Please <a href="http://remotestaff.com.au/portal/jobseeker/autologin.php?c=69bafacf5bda9908c054db5436b37e2e6ff1ff7a" target="_blank" title="This external link will open in a new window">CLICK HERE</a>
    to update your resume. <br>This will allow us to asses and match you accordingly to our <a href="http://www.remotestaff.com.ph/jobopenings.php?jr_cat_id=1&amp;category_id=4" target="_blank" title="This external link will open in a new window">Current Job Openings</a>.
</p>
<p>


    If NO, please <a href="http://remotestaff.com.au/portal/jobseeker/in.php?c=69bafacf5bda9908c054db5436b37e2e6ff1ff7a" target="_blank" title="This external link will open in a new window">CLICK HERE</a>.
    <br>We will remove your resume from our website but will keep your profile for future reference..
</p>
<br>
<p>
    You may also reply to this email with the following if you are still interested
</p>
<ol type="a">
    <li style="margin-bottom:8px;">Complete Name</li>
    <li style="margin-bottom:8px;">Birthday</li>
    <li style="margin-bottom:8px;">Email Ad</li>
    <li style="margin-bottom:8px;">Mobile Number</li>
    <li style="margin-bottom:8px;">Last Job Title</li>
    <li style="margin-bottom:8px;">Attach a Resume</li>
</ol>
<p >
    This email has been sent to you because you have applied on our website <a href='www.remotestaff.com.ph'>www.remotestaff.com.ph</a> last <?php echo $datecreated ?>.
</p>

<p>
    Best regards,
</p>
<?php echo $signature_template?>