<p>
    Dear <?php echo $staff_name; ?>,
</p>

<p>
    This is to confirm your availability.
</p>

<p>
    We would like to know if you are still looking for a job and still interested to join Remote Staff to have a long lasting work from home/office job. Knowing your background and skill sets we are confident that we will find a client for you to work with soon.

</p>

<p>
    Please let me know of your availability by responding to this email with your current work set up and updated comprehensive resume so we can either retain or remove you from our Available Staff List. If I don't get a response within 2 business days from the date of this email I will assume that you are no longer interested and remove you off our list.
</p>

<p>
    Hope to hear from you soon.
</p>
<p>
    Requirements for Home-Based Job:
</p>
<ul>
    <li style="margin-bottom:8px;">DSL Connection of at least 1mbps</li>
    <li style="margin-bottom:8px;">Desktop or Laptop working with the latest OS</li>
    <li style="margin-bottom:8px;">Headset</li>
    <li style="margin-bottom:8px;">Webcam</li>
    <li style="margin-bottom:8px;">No Full Time work</li>
</ul>
<br>
<p>
    Regards,
</p>
<?php echo $signature_template?>