<p>

    Dear <?php echo $staff_name; ?>,
</p>

<p>

    You are given 2 days to accomplish profile updates and the attached questionnaire/s to further process your application.
    Having your online profile up-to-date would boost your profile and have it immediately noticed by our clients. <strong ><u style="color:red;">Unable to do so will make your profile inactive.</u></strong>
</p>

<p>

    <ol type="1">

        <li style="margin-bottom:8px;">Kindly email a copy of your <strong><u>comprehensive</u> resume with work experience/s and <u>detailed job description.</u></strong> Please include <strong>all awards and commendations</strong> received from employers.</li>
        <li style="margin-bottom:8px;">Please complete your portfolio on our portal (use your email ad for the username and login as a JOBSEEKER): <a href="http://www.remotestaff.com.ph">www.remotestaff.com.ph</a> ; you can also <a href="https://remotestaff.com.au/portal/forgotpass.php?user=applicant">CLICK HERE</a> to retrieve your password.</li>
        <li style="margin-bottom:8px;">Fill in <strong>"Skills"</strong> (All Technical and Non-Technical), as applicable to you and related to work you are applying for.  Note: More Skills, the better <strong>(at least 10).</strong></li>
        <li style="margin-bottom:8px;">All <strong>Languages</strong> you are fluent with</li>
        <li style="margin-bottom:8px;">Specify your <strong>expected salary.</strong></li>
        <li style="margin-bottom:8px;"><strong>Skype ID</strong> and other contact details.</li>
        <li style="margin-bottom:8px;"><strong>Devices and Gadgets</strong> you have at home needed for Home-based job (Computer, Internet package/bandwidth, Headset, webcam, etc.)</li>
        <li style="margin-bottom:8px;">Link to the <strong>speedtest result</strong> via <a href="http://www.speedtest.net">CLICK HERE</a></li>
        <li style="margin-bottom:8px;">Upload a recent <strong><u>collared</u></strong> picture.</li>
        <li style="margin-bottom:8px;">Upload a <strong>voice recording</strong>, <strong style="color:red;">one in English and another in any other Foreign language(s) that you are fluent with. <u>Please create different files for each language</u></strong>, with this template:

            <br>
<p style="margin-bottom:8px;"><i>Hi!</i></p>
<p style="margin-bottom:8px;"><i>I have been working since (year) related to (field:Customer Service, technical support, Accounting, Inbound/outbound Telemarketing, others) with __________ (industry: automotive, IT, retail, real estate) company/ies. </i></p>
<p style="margin-bottom:8px;"><i>I am proud to say that I am skilled and well knowledgeable on (mention all important skills/softwares/tools related to the field: Customer handling, Customer satisfaction, PHP, SEO, HTML, Magento, Joomla, Payroll, Inventories, HR, Audit, Recruitment, Sourcing, etc).</i> </p>
<p style="margin-bottom:8px;"><i>I also have <strong>basic</strong> knowledge and background on _________ (mention other skills/softwares/tools related to your career/expertise).</i></p>
<p style="margin-bottom:8px;"><i>In line with this, I was awarded and/or was commended on (customer satisfaction, attendance, quality, top-agent, loyalty, etc related to field or work experiences). </i></p>
<p style="margin-bottom:8px;"><i>On the other hand, I enjoy and love ____________ (Hobbies: singing, dancing, sports, shopping, travelling, cooking,etc.).</i></p>
<br><br>
<ul style="list-style-type:disc">
    <li style="margin-bottom:8px;">Please stick with this template - No last name and no company/employer's name.</li>
    <li style="margin-bottom:8px;">Make sure that your recording is <strong>clear</strong>, <strong>no static,no background noise, and can be understood.</strong> Be specific and detailed. Just be yourself. <strong>Be lively.</strong></li>
    <li style="margin-bottom:8px;"><strong>Must be in WAV, Mpeg, WMA, or MP3 file.</strong></li>
    <li style="margin-bottom:15px;">In any case that you are having problems on uploading your picture or voice recording, please do not hesitate to send me the file/s so I could upload it on your profile.</li>
</ul>
</li>

</ol>


<p>Let me know when you're done, you can either SMS or email me so we could setup an initial interview via SKYPE and further process your application. Please add me on SKYPE so we could set you up for an initial interview. <strong style="color:red;">We will prioritize candidates with completed profile.</strong>  </p>

<p><strong>Requirements for Home-Based Job:</strong></p>
<ul>
    <li style="margin-bottom:8px;">DSL Connection of at least 1mbps</li>
    <li style="margin-bottom:8px;">Desktop or Laptop working with the latest OS</li>
    <li style="margin-bottom:8px;">Headset</li>
    <li style="margin-bottom:8px;">Webcam</li>
    <li style="margin-bottom:8px;">No Full Time work</li>
</ul>

</p>
<br>
<p>Thank you, </p>
<?php echo $signature_template?>