<p>
    Dear <?php echo $staff_name; ?>,
</p>
<p>
    Confirming your SKYPE interview with the following details:
</p>
<p>
    Please log in to Skype on <b>[Date] [Time – 24hrs] Manila Time</b>. Be online and message me at least <b>15 MINUTES PRIOR</b> the schedule and make sure to use a <b>WIRED internet connection</b>, Laptop or Desktop, headset and webcam. Kindly add <b>[RS Skype ID]</b> on Skype.
</p>
<p >
    I have noticed that your resume is not yet complete. For the interview to be seamless and quick and for us to easily evaluate whether you are qualified or not, please update your resume by following quick and simple steps below.
</p>

<ul>

    <li style="margin-bottom:8px;">Log in as a JobSeeker at<a href="https://remotestaff.com.au/portal/"> https://remotestaff.com.au/portal/</a> . If you are unsure about your password, get it here <a href="https://remotestaff.com.au/portal/forgotpass.php?user=applicant">https://remotestaff.com.au/portal/forgotpass.php?user=applicant</a>.</li>
    <li style="margin-bottom:8px;">Once logged in, under the Control Panel Box on the left hand side of the page, Click on the resume areas you want to update. Update your resume add as much details as you know.</li>
    <li style="margin-bottom:8px;">Ensure that you have a voice recording uploaded. It is <b>VERY important to upload a voice recording</b> as applicants with voice recording get hired sooner than those who don't. The voice recording identifies your spoken English skills which is very important as the Clients looking for staff are from the US, UK and Australia. The voice recording should be minimum 60 seconds and maximum 150 seconds in length. Follow the template provided on the “Profile Completion” email we sent you before this email.</li>

</ul>
<p>
    Should you have any questions, feel free to contact me through my contact details below.
</p>



<ul>

    <li style="margin-bottom:8px;">Mobile number:</li>
    <li style="margin-bottom:8px;">Skype:</li>

</ul>
<p><strong>TAKE NOTE:</strong></p>
<ul>

    <li style="margin-bottom:8px;">Failure to show up on confirmed interview schedule will be subject for an evaluation before a reschedule may be granted.</li>
    <li style="margin-bottom:8px;">Remote Staff also has the right to consider your application as BLACKLISTED if you fail to attend succeeding interviews, rescheduled or otherwise, that you have confirmed to.</li>
    <li style="margin-bottom:8px;">If something comes up that will prevent you from attending the interview, please inform us at least 3 Hours before the interview schedule and NOT AFTER the schedule has elapsed.</li>
</ul>
<p >
    Kindly reply on this email to confirm.
</p>
<br>



<p>Regards,</p>
<?php echo $signature_template?>